#!/bin/bash

[[ $0 != $BASH_SOURCE ]] && SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )" || SCRIPT_DIR="$( cd "$( dirname "$-1" )" && pwd )"

! test -f $SCRIPT_DIR/reade &&
printf "'reade' needs to be in the same folder as 'readyn' for it to work\n" &&
exit 1 ||
source $SCRIPT_DIR/reade

function readyn(){

    [[ $0 != $BASH_SOURCE ]] && SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )" || SCRIPT_DIR="$( cd "$( dirname "$-1" )" && pwd )"

    red=$(tput setaf 1)
    red1=$(tput setaf 9)
    green=$(tput setaf 2)
    green1=$(tput setaf 10)
    yellow=$(tput setaf 3)
    yellow1=$(tput setaf 11)
    blue=$(tput setaf 4)
    blue1=$(tput setaf 12)
    magenta=$(tput setaf 5)
    magenta1=$(tput setaf 13)
    cyan=$(tput setaf 6)
    cyan1=$(tput setaf 14)
    white=$(tput setaf 7)
    white1=$(tput setaf 15)
    black=$(tput setaf 16)
    grey=$(tput setaf 8)

    RED=$(tput setaf 1 && tput bold)
    RED1=$(tput setaf 9 && tput bold)
    GREEN=$(tput setaf 2 && tput bold)
    GREEN1=$(tput setaf 10 && tput bold)
    YELLOW=$(tput setaf 3 && tput bold)
    YELLOW1=$(tput setaf 11 && tput bold)
    BLUE=$(tput setaf 4 && tput bold)
    BLUE1=$(tput setaf 12 && tput bold)
    MAGENTA=$(tput setaf 5 && tput bold)
    MAGENTA1=$(tput setaf 13 && tput bold)
    CYAN=$(tput setaf 6 && tput bold)
    CYAN1=$(tput setaf 14 && tput bold)
    WHITE=$(tput setaf 7 && tput bold)
    WHITE1=$(tput setaf 15 && tput bold)
    BLACK=$(tput setaf 16 && tput bold)
    GREY=$(tput setaf 8 && tput bold)

    bold=$(tput bold)
    underline_on=$(tput smul)
    underline_off=$(tput rmul)
    bold_on=$(tput smso)
    bold_off=$(tput rmso)
    half_bright=$(tput dim)
    reverse_color=$(tput rev)

    # Reset
    normal=$(tput sgr0)

    # Broken !! (Or im dumb?)
    blink=$(tput blink)
    underline=$(tput ul)
    italic=$(tput it)
         

    VERSION='1.0' 

    while :; do
        case $1 in
            -h|-\?|--help|'')
                printf "     ${bold}readyn${normal} [ -h/--help ] [ -v/--version ]  [ -y/--yes [ PREFILL ] ]  [ -n/--no [ CONDITION ] ] [ -p/--prompt PROMPTSTRING ] [ -Q/--colour COLOURSTRING ]  [ -b/--break-chars BREAK-CHARS ] [ returnvar ]\n
         Simplifies yes/no prompt for ${bold}reade${normal}. 
         Takes at least one argument, otherwise will prompt help page.
         
         Like 'read' and 'reade', supply at a variable as the last argument for the return value. 
         Otherwise the value will be in the '\$REPLY' and '\$READE_VALUE'.    
         '${GREEN} [${underline_on}Y${underline_off}es/${underline_on}n${underline_off}o]: ${normal}' : 'y' as pre-given, 'n' as other option. Colour for the prompt is ${GREEN}GREEN (Default)${normal} 
         '${YELLOW} [${underline_on}N${underline_off}o/${underline_on}y${underline_off}es]: ${normal}' : 'n' as pre-given, 'y' as other option. Colour for the prompt is ${YELLOW}YELLOW${normal}
         For both an empty answer will return the default answer. 

        -h, --help  
            
            Print this text and exit
         
        -p, --prompt ${underline_on}PROMPTSTRING${underline_off} 

            Prompt to supply. At the end of the prompt '[${underline_on}Y${underline_off}es/${underline_on}n${underline_off}o]: ' or '[${underline_on}N${underline_off}o/${underline_on}y${underline_off}es]: ' will appear.  

        -y, --yes [ ${underline_on}prefill${underline_off} ], [[ ${underline_on}prefill-prompt${underline_off} ]] 
            Set to 'Yes' prompt with 2 optional, comma-separated arguments 
            Pregiven is 'y' without argument, otherwise first becomes pregiven. 
            Second optional is the prefill word in coloured prompt ([Word]), otherwise defaults to '[${underline_on}Y${underline_off}es/${underline_on}n${underline_off}o]: ' 

        -n, --no [ ${underline_on}prefill${underline_off} ], [[ ${underline_on}prefill-prompt${underline_off} ]] 
            Same as for --yes but 'no' variant
            Default pregiven is 'n', prompt word in prompt defaults to '[${underline_on}N${underline_off}o/${underline_on}y${underline_off}es]: ' when only '--no' is supplied
            
            If neither '--no' or '--yes' are active => yes-prompt 

        -c, --condition ${underline_on}CONDITION${underline_off} 

            At default will prefer to prompt the '--no' flag over the '--yes' flag. 
            If you only want the '--no' prompt to be applicable when a given condition is active then give it up as an argument in a string. 

        -Y, --yes-colour ${underline_on}COLOUR${underline_off}
            Default: ${GREEN}GREEN${normal} 

        -N, --no-colour ${underline_on}COLOUR${underline_off}
            Default: ${YELLOW}YELLOW${normal} 

            Only active if --yes(Default)/--no applicable. 
            Use  one  of  the  colour names black, red, green, yellow, blue, cyan, purple (=magenta) or white, or an ANSI-conformant <colour_spec> to colour any prompt displayed  by  command.\n\tAn uppercase colour name (Yellow or YELLOW ) gives a bold prompt.\n Prompts that already contain (colour) escape sequences or one of the readline \"ignore markers\" (ASCII 0x01 and 0x02) are not coloured.

        -a, --auto 
            
            Fill in with the pregiven immediately

        -b ${underline_on}list_of_characters${underline_off} 

            (Applicable when ${bold}rlwrap${normal} installed - from manual):
            Consider  the specified characters word-breaking (whitespace is always word-breaking). 
            This determines what is considered a \"word\", both when completing and when building a completion word list from files specified by -f options following (not preceding!) it.
            Default list (){}[],'+-=&^%%\$#@\";|\  
            Unless -c is specified, / and . (period) are included in the default list\n\n"
            return 0
          ;;
          -v|--version) 
             printf "${bold}Version${normal} : $VERSION\n"
             return 0
          ;; 

          # Otherwise 
          *) break 
          ;;
       esac
    done && OPTIND=1;


    #https://stackoverflow.com/questions/12022592/how-can-i-use-long-options-with-the-bash-getopts-builtin

    for arg in "$@"; do
      shift
      case "$arg" in
        '--yes')               set -- "$@" '-y'   ;;
        '--no')                set -- "$@" '-n'   ;;
        '--yes-colour')        set -- "$@" '-Y'   ;;
        '--auto')              set -- "$@" '-a'   ;;
        '--no-colour')         set -- "$@" '-N'   ;;
        '--prompt')            set -- "$@" '-p'   ;;
        '--condition')         set -- "$@" '-c'   ;;
        '--break-chars')       set -- "$@" '-b'   ;;
        *)                     set -- "$@" "$arg" ;;
      esac
    done 

    breaklines=''
    condition='' 
    pre='y'
    pre_y='y'
    pre_n='n' 
    othr='n' 
    prmpty="${underline_on}Y${underline_off}es"
    prmptn="${underline_on}n${underline_off}o"
    ycolor='GREEN' 
    ncolor='YELLOW' 
    color="$ycolor" 
    ygivn=0, ngivn=0 
    preff=''
    auto=''
    OPTIND=1
    while getopts 'anyb:Y:N:c:p:y:n:' flag; do
        case "${flag}" in
             a)  auto='y' 
                 ;;
             b) if [ "${OPTARG}" ] && ! test "${OPTARG}" == '--' && ! [[ ${OPTARG} =~ ^-.* ]]; then 
                    breaklines="-b \"${OPTARG}\"";
                fi 
                if [[ ${OPTARG} =~ ^-.* ]]; then
                    OPTIND=$(($OPTIND - 1)) 
                fi
             ;;    
             Y) if [ "${OPTARG}" ] && ! test "${OPTARG}" == '--' && ! [[ ${OPTARG} =~ ^-.* ]]; then 
                    ycolor="${OPTARG}";
                fi
                if [[ ${OPTARG} =~ ^-.* ]]; then
                    OPTIND=$(($OPTIND - 1)) 
                fi
             ;;    
             N) if [ "${OPTARG}" ] && ! test "${OPTARG}" == '--' && ! [[ ${OPTARG} =~ ^-.* ]]; then
                    ncolor="${OPTARG}";
                fi
                if [[ ${OPTARG} =~ ^-.* ]]; then
                    OPTIND=$(($OPTIND - 1)) 
                fi 
             ;;    
             p) if [ "${OPTARG}" ] && ! test "${OPTARG}" == '--' && ! [[ ${OPTARG} =~ ^-.* ]]; then
                    prmpt="${OPTARG}";
                fi
                if [[ ${OPTARG} =~ ^-.* ]]; then
                    OPTIND=$(($OPTIND - 1)) 
                fi 
             ;;
             y)  preff='y'
                 args='' 
                 if [ "${OPTARG}" ] && ! test "${OPTARG}" == '--' && ! [[ ${OPTARG} =~ ^-.* ]]; then

                    # disable glob 
                    set -f 

                    # split on space characters 
                    IFS=',' 

                    args=($OPTARG);
                    pre_y="${args[0]}" 
                    ! test -z "${args[1]}" && prmpty="${args[1]}" 
                else
                    pre='y' 
                    prmpty="${underline_on}Y${underline_off}es"
                    prmptn="${underline_on}n${underline_off}o" 
                    if [[ ${OPTARG} =~ -.* ]]; then
                        OPTIND=$(($OPTIND - 1)) 
                    fi
                fi
                #if ! test -z "$condition" && ! ${condition} || test -z "$condition" ; then
                #    pre='y'
                #    othr='n'
                #    color="$ycolor" 
                #fi
                ;;

            n)  preff='n'
                args='' 
                if [ "${OPTARG}" ] && ! test "${OPTARG}" == '--' && ! [[ ${OPTARG} =~ ^-.* ]]; then
                    set -f 
                    IFS=',' 
                    args=($OPTARG);
                    pre_n="${args[0]}"
                    ! test -z "${args[1]}" && prmptn="${args[1]}"  
                else
                    pre='n'
                    prmptn="${underline_on}N${underline_off}o"
                    prmpty="${underline_on}y${underline_off}es" 
                    if [[ ${OPTARG} =~ ^-.* ]]; then
                        OPTIND=$(($OPTIND - 1)) 
                    fi
                fi
                ;; 

              c) if [ "${OPTARG}" ] && ! test "${OPTARG}" == '--' && ! [[ ${OPTARG} =~ ^-.* ]]; then
                    condition="${OPTARG}"
                fi 
                if [[ ${OPTARG} =~ ^-.* ]]; then
                    OPTIND=$(($OPTIND - 1)) 
                fi 
                ;;
        esac
    done 

    shift $((OPTIND-1)) 

    if test -z "$preff" || test "$preff" == 'y'; then
        prmpt1=" [$prmpty/$prmptn]: "
        color="$ycolor"
        pre=$pre_y 
        othr=$pre_n 
    else
        prmpt1=" [$prmptn/$prmpty]: "
        color="$ncolor"
        pre=$pre_n 
        othr=$pre_y 
    fi

    if ! test -z "$condition" && eval "${condition}"; then
        test "$prmptn" == "${underline_on}n${underline_off}o" && prmptn="${underline_on}N${underline_off}o"  
        test "$prmpty" == "${underline_on}Y${underline_off}es" && prmpty="${underline_on}y${underline_off}es"  
        prmpt1=" [$prmptn/$prmpty]: "
        color="$ncolor"
        pre=$pre_n 
        othr=$pre_y 
    fi

    if ! test -z $auto; then
        if test -z "$prmpt"; then
            printf "${!color}$prmpt1$pre${normal}\n";   
        else
            printf "${!color}$prmpt$prmpt1$pre${normal}\n";   
        fi
        vvvvvvvvvv=$pre 
    else
        if test -z "$prmpt"; then
            reade -Q "$color" $breaklines -i "$pre $othr" -p "$prmpt1" vvvvvvvvvv;   
        else
            reade -Q "$color" $breaklines -i "$pre $othr" -p "$prmpt$prmpt1" vvvvvvvvvv;    
        fi
         
    fi 

    export READE_VALUE="$vvvvvvvvvv" 
    export REPLY="$vvvvvvvvvv" 

    if ! test $# -eq 0; then
        eval "${@:$#:1}=$vvvvvvvvvv" 
    fi

    unset pre other prmpt prmpt1 color readestr breaklines SCRIPT_DIR 
}

#readyn $@
